jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: Build with Gradle
      uses: ./gradlew build --no-daemon
      with:
        arguments: build
    - continue-on-error: true
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        USERNAME: ${{ github.actor }}
      name: Publish to GitHub Packages
      uses: ./gradlew build --no-daemon
      with:
        arguments: publish
name: Gradle Package
on:
  repository_dispatch:
    types: trigger-ga___gradle-publish.yml
